// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjmwuzbikwmowywrmrdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqbXd1emJpa3dtb3d5d3JtcmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjQ4NTMsImV4cCI6MjA3MTQ0MDg1M30.sfeVPi3iKrv9MGcL0lUNidqGOGuTl5N_jcrNvJfy-xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});